apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: u0bxb2lgz-go 
  janus-idp.io/tekton: u0bxb2lgz-go
  backstage.io/kubernetes-id: u0bxb2lgz-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: u0bxb2lgz-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  